# 端口和根路径，jar启动时依此处配置，放tomcat后以tomcat的配置为准
server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  compression:
    enabled: true
    min-response-size: 2048
  tomcat:
    # tomcat容器层最大传输限制，不做限制
    max-http-post-size: -1
    max-http-form-post-size: -1
    max-swallow-size: -1

oss: minio

# 整个文档项目的配置
zyplayer:
  doc:
    # ------zyplayer_doc_manage相关配置------
    manage:
      # 管理端的数据库配置
      datasource:
        driverClassName: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
        url: jdbc:mysql://${DATASOURCE_HOST_PORT:mac:3306}/${DATASOURCE_DATABASE:zyplayer_doc}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: ${DATASOURCE_USER:root}
        password: ${DATASOURCE_PASSWORD:123456}
      # 版本和升级信息获取地址
      upgradePropertiesUrl: https://gitee.com/zyplayer/zyplayer-doc/raw/master/upgrade.properties
      # 系统根域名，调试UI时需要使用，同时需要在host文件里配置：127.0.0.1 local.zyplayer.com
      originDomainRegex: .*\.zyplayer\.com(:\d+|)$
    # ------WIKI文档相关------
    wiki:
      # WIKI文档的文件上传后的存储目录
      upload-path: ${WIKI_UPLOAD_PATH:D:/zyplayerDoc/wikiFiles}
      # 是否检查目录有被系统定期清理的风险，建议开启
      upload-path-check: true

spring:
  application:
    name: zyplayer-doc
  servlet:
    multipart:
      max-file-size: ${SERVLET_MAX_FILE_SIZE:100MB}
      max-request-size: ${SERVLET_MAX_REQUEST_SIZE:100MB}
  datasource:
    continue-on-error: true
