version: '3.8'

services:
  # MySQL 5.7 数据库服务
  mysql:
    image: mysql:5.7
    container_name: mysql_doc
    restart: always
    environment:
#      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zyplayer_doc
      MYSQL_USER: doc
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # MinIO 对象存储服务
  minio:
    image: minio/minio:RELEASE.2023-01-12T02-06-16Z
    container_name: zyplayer-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      TZ: Asia/Shanghai
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Spring Boot 应用服务
  zyplayer-doc:
    build:
      context: .
      dockerfile: Dockerfile
    image: zyplayer-doc:latest
    container_name: zyplayer-doc-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATASOURCE_HOST_PORT: localhost
      DATASOURCE_USERNAME: doc
      SPRING_DATASOURCE_PASSWORD: 123456
      MINIO_ENDPOINT: http://localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      OSS_TYPE: minio
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local
